/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prolog_map;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author karli
 */
public class Map extends javax.swing.JFrame {
    
    private String Inicio;
    private String Fin;

    public Map(String Inicio, String Fin) {
        this.Inicio = Inicio;
        this.Fin = Fin;
    }
   
    

    /**
     * Creates new form Map
     */
    public Map() {
        initComponents();
        setResizable(false);
        setSize(1366, 768);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
        @Override
    public void paint(Graphics g){
        Graphics2D g2d = (Graphics2D) g;
        Image fondo = new ImageIcon(getClass().getResource("/image/Mapa_SantaTecla3.png")).getImage();
        
        g2d.drawImage(fondo, 0, 0, this); // 0, 0 indica la posición inicial de la imagen
        
        
        Stroke grosorLinea = new BasicStroke(3.8f); // 
        g2d.setStroke(grosorLinea);
        g2d.setColor(Color.BLUE);
        
        List<Coordenadas> lista = new ArrayList<>();
        
        lista.add(new Coordenadas(313,286));
        lista.add(new Coordenadas(547,297));
        lista.add(new Coordenadas(640,296));
        lista.add(new Coordenadas(640,325));
        
        
        
        for (int i = 0; i < lista.size(); i++) {
            
            if(i == 0){
                g2d.fillOval(lista.get(i).getX() - 5,lista.get(i).getY() - 5, 15, 15);
            }
            
            if(i != lista.size() - 1){
                
                g2d.drawLine(lista.get(i).getX(),lista.get(i).getY() , 
                             lista.get(   i+1).getX(),lista.get(i+1).getY());
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
